module.exports = {
  printWidth: 200,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  vueIndentScriptAndStyle: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  bracketSpacing: true,
  trailingComma: 'es5',
  jsxSingleQuote: false,
  arrowParens: 'avoid',
  insertPragma: false,
  requirePragma: false,
  proseWrap: 'never',
  htmlWhitespaceSensitivity: 'ignore',
  endOfLine: 'auto',
  rangeStart: 0,
};
